name: CI

on: [push, pull_request]

jobs:

  build_xbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ARK
        run: |
          chmod +x dependencies/python/configure_build.py
          dependencies/python/configure_build.py xbox
          chmod +x dependencies/linux/ninja
          dependencies/linux/ninja
      - name: Remove .gitkeep
        run: |
          find . -name ".gitkeep" -type f -delete
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: DC3DX-Xbox
          path: out/xbox
          #
  build_debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup env
        run: |
          pwd
          mkdir -p ./platform/debug
          mkdir -p ./platform/debug/gen
          cp dependencies/dbg_patcher/main_xbox.hdr platform/debug/gen/main_xbox.hdr
          truncate -s 22353239 platform/debug/gen/main_xbox_0.ark
          truncate -s 5721833 platform/debug/gen/main_xbox_1.ark
          truncate -s 24584681 platform/debug/gen/main_xbox_2.ark
          truncate -s 266057007 platform/debug/gen/main_xbox_3.ark
          truncate -s 688887924 platform/debug/gen/main_xbox_4.ark
          truncate -s 107950925 platform/debug/gen/main_xbox_5.ark
          truncate -s 468328063 platform/debug/gen/main_xbox_6.ark
          truncate -s 22352016 platform/debug/gen/main_xbox_7.ark
          truncate -s 1983799220 platform/debug/gen/main_xbox_8.ark
          truncate -s 300667016 platform/debug/gen/main_xbox_9.ark
      - name: Build ARK
        run: |
          chmod +x dependencies/python/configure_build.py
          dependencies/python/configure_build.py debug
          chmod +x dependencies/linux/ninja
          dependencies/linux/ninja
      - name: Remove .gitkeep
        run: |
          find . -name ".gitkeep" -type f -delete
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: DC3DX-Debug
          path: out/debug
          #          